version: '3'

services:
  
  apache:
    image: ${PROJECT_NAME}/apache
    container_name: ${PROJECT_NAME}-apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf.d:/etc/apache2/conf.d
     - ./apache/ssl:/etc/apache2/ssl
     - ./apache/logs:/var/log/apache2
     - ../public:/var/www/html

  mysql:
    image: ${PROJECT_NAME}/mysql
    container_name: ${PROJECT_NAME}-mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}-mailhog
    ports:
      - 8025:8025
      - 25:1025
